Repository mostafaboustani/Soen-341, pull requests merged in 2020-03, with the labels that each got.

#49 Added functioning Travis Test which should close #47
  .travis.yml
  server/database/default.json
Labels: TravisCI

#59 Fix mongoDB server (#57)
  client/package.json
  server/index.js
  server/package.json
Labels: bug

#66 Organization and Re-Structure for sprint 4 #65
  client/src/App.css
  client/src/App.js
  client/src/authentication/auth-login.js
  client/src/authentication/setAuthenticationToken.js
  client/src/components/following.js
  client/src/components/login.js
  client/src/components/maxresdefault.jpg
  client/src/components/navbar.js
  client/src/components/photoupload.js
  client/src/components/profile.js
  client/src/components/profiledetails.js
  client/src/components/signup.js
  client/src/index.js
  client/src/pages/loginsignup.js
  client/src/pages/managefollowing.js
  client/src/pages/profilepage.js
  client/src/styling/loginstyle.css
  client/src/styling/signupstyle.css
  server/index.js
  server/package.json
  server/routes/currentUser.js
  server/routes/following.js
  server/tests/testAuthentication.js
Labels: organization

#72 Issue #71 Fix Travis Test
  server/tests/testAuthentication.js
Labels: Patch

#74 profile page layout, photo descriptions, bio, and "followers" functionality.
  client/src/App.css
  client/src/components/displayPictures.js
  client/src/components/photoupload.js
  client/src/components/profiledetails.js
  client/src/index.js
  client/src/pages/homepage.js
  client/src/pages/profilepage.js
  server/index.js
  server/models/user-schema.js
  server/package.json
  server/routes/following.js
  server/routes/loginUser.js
  server/routes/registerUser.js
  server/routes/updateBio.js
Labels: To be forked

#75 Issue #61 Search and View other Profiles
  client/package.json
  client/src/App.js
  client/src/components/following.js
  client/src/components/navbar.js
  client/src/components/profiledetails.js
  client/src/components/searchdisplaypictures.js
  client/src/components/searchprofiledetails.js
  client/src/pages/managefollowing.js
  client/src/pages/profilepage.js
  client/src/pages/searchprofilepage.js
  server/index.js
  server/routes/searchUser.js
Labels: enhancement, new feature
